# Generated by Django 5.0 on 2024-02-25 09:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(max_length=200, verbose_name='Tweet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='Yazar')),
                ('like', models.ManyToManyField(related_name='likes', to='user.profile', verbose_name='Beğenenler')),
                ('retweet', models.ManyToManyField(related_name='retweets', to='user.profile', verbose_name='Retweet edenler')),
                ('saves', models.ManyToManyField(related_name='saves', to='user.profile', verbose_name='Kaydedenler')),
                ('view', models.ManyToManyField(related_name='views', to='user.profile', verbose_name='Görüntüleyenler')),
            ],
            options={
                'verbose_name': 'Tweet',
                'verbose_name_plural': 'Tweetler',
                'ordering': ['-created_at'],
            },
        ),
    ]
