# Generated by Django 5.0 on 2024-03-09 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
        ('user', '0002_alter_profile_follow_alter_profile_follower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='İşlem Mesajı')),
                ('islem', models.CharField(choices=[('begeni', 'Beğeni'), ('retweet', 'Retweet'), ('yorum', 'Yorum'), ('takip', 'Takip')], max_length=100, verbose_name='İşlem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Yapılan Tarih')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='İşlem Yapılan Post')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='Bildirim Alan')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderen', to='user.profile', verbose_name='Bildirim Gönderen/İşlem Yapan')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
            },
        ),
    ]
