# Generated by Django 5.0 on 2024-03-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_notificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificate',
            name='isRead',
            field=models.BooleanField(default=False, verbose_name='Okundu bilgisi'),
        ),
    ]
