# Generated by Django 5.0 on 2024-03-09 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_notificate_isread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificate',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='İşlem Yapılan Post'),
        ),
    ]
